name: Generate Hagezi RuleSets

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_DIR: dist
      VERSION_FILE: VERSION.txt
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set ENV variables
        run: |
          echo "RELEASE_NAME=$(TZ="Asia/Shanghai" date --iso-8601=minutes)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date --utc '+%FT%H.%M')" >> $GITHUB_ENV
        shell: bash

      - name: Generate MiHomo mrs rules
        shell: bash
        run: |
          set -euo pipefail
          MIHOMO_URL=$(curl -s -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | jq -r '.assets[] | select(.name | test("mihomo-linux-amd64-v.*\\.gz$")) | .browser_download_url' | head -n 1)
          curl -sSLf "$MIHOMO_URL" -o mihomo.gz
          gunzip mihomo.gz
          chmod +x mihomo
          echo set action var in repo setting like this: DATASET_BASH='declare -A DATASET=([pro]="Pro" [pro.mini]="ProMini" [gambling.mini]="GamblingMini" [native.oppo-realme]="Oppo")'
          eval "${{ vars.DATASET_BASH }}"
          HaGeZi_PREFIX="https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard"
          for version in "${!DATASET[@]}"; do
            filename="${DATASET[$version]}"
            curl -sSLf "${HaGeZi_PREFIX}/${version}-onlydomains.txt" -o "Temp${filename}.txt"
            sed -e '/^#/d' -e 's/^/+./' "Temp${filename}.txt" > "${filename}.txt"
            ./mihomo convert-ruleset domain text "${filename}.txt" "${filename}.mrs"
            upstream_ver=$(awk '/Version:/{print $NF; exit}' "Temp${filename}.txt")
          done
          echo "HaGeZi version: $upstream_ver" > $VERSION_FILE

      - name: Delete temp files
        run: |
          rm -v mihomo Temp*.txt

      - name: Move files to publish directory
        run: |
          mkdir -p $RELEASE_DIR
          cp -v -t $RELEASE_DIR *.txt *.mrs

      - name: Release and upload assets
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          body_path: ${{ env.VERSION_FILE }}
          prerelease: false
          working_directory: ${{ env.RELEASE_DIR }}
          files: |
            *.mrs

      - name: Git push assets to "release" branch
        run: |
          cd $RELEASE_DIR || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${RELEASE_NAME}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin release

      - name: Purge jsdelivr CDN
        run: |
          cd $RELEASE_DIR || exit 1
          for file in *.mrs; do
            curl -si "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/${file}"
          done
